# my_config.yaml

# PARAMETERS
year: '2020'

##########################################################################################

# LOGGING
logging:
  root_level: INFO
  file_level: DEBUG
  console_level: DEBUG

##########################################################################################

# PATHS
data_path: data/raw/credit-risk.xlsx
mappings_path: data/mapping/dtype_mappings.json
processed: data/interim/processed.parquet

path:
  eval_report: reports/analysis/eval_reports
  sector_map: reports/analysis/maps
  correlation: reports/analysis/correlation
  exploration: reports/figures
  skew: reports/analysis/skew_analysis
  maps: reports/analysis/maps
  eigen: reports/analysis/eigenvalues

##########################################################################################

# LISTS
export_tables:
  - t1_20k
  - t20k_40k
  - t40k_60k
  - t60k_80k
  - t80k_100k
  - t100k_121k
  # - tdescription

continuous:
  - Turnover.
  - EBIT.
  - PLTax.
  - Leverage.
  - ROE.
  - TAsset.

raw_features:
  - Turnover.
  - EBIT.
  - PLTax.
  # - MScore.
  - Leverage.
  - ROE.
  - TAsset.

growth_features:
  - growth_TAsset
  - growth_EBIT
  # - growth_MScore.
  - growth_PLTax
  - growth_Turnover
  - growth_Leverage
  - growth_ROE

volatility_features:
  - volatility_TAsset
  - volatility_EBIT
  # - volatility_MScore
  - volatility_PLTax
  - volatility_Turnover
  - volatility_Leverage
  - volatility_ROE

further_features:
  - fur_debt_to_eq
  - fur_op_marg
  - fur_asset_turnover
  - fur_roa

trans_idx:
  - log
  - sqrt
  - inv_sqrt
  - inv
  - power
