# my_config.yaml

# PARAMETERS
year: '2020'

##########################################################################################

# LOGGING
logging:
  root_level: DEBUG
  file_level: DEBUG
  console_level: DEBUG

##########################################################################################

# PATHS
data_path: data/raw/credit-risk.xlsx
mappings_path: data/mapping/dtype_mappings.json
processed: data/interim/processed.parquet

path:
  interim: data/interim
  eval_report: reports/analysis/eval_reports
  correlation: reports/analysis/correlation
  exploration: reports/figures
  variance: reports/analysis/variance
  skew: reports/analysis/skew_analysis
  maps: reports/analysis/maps
  eigen: reports/analysis/eigenvalues

##########################################################################################

# LISTS
export_tables:
  - t1_20k
  - t20k_40k
  - t40k_60k
  - t60k_80k
  - t80k_100k
  - t100k_121k
  # - tdescription


nominal:
- Company name
- Region
- Country
- NACE code
- Sector 1
- Sector 2
- Combined_Sector

ordinal:
- MScore_mean
- growth_MScore_mean
- volatility_MScore

continuous:
- TAsset_mean
- Leverage_mean
- EBIT_mean
- Turnover_mean
- ROE_mean
- PLTax_mean
- growth_TAsset_mean
- growth_Leverage_mean
- growth_EBIT_mean
- growth_Turnover_mean
- growth_ROE_mean
- growth_PLTax_mean
- volatility_TAsset
- volatility_Leverage
- volatility_EBIT
- volatility_Turnover
- volatility_ROE
- volatility_PLTax
- fur_debt_to_eq
- fur_op_marg
- fur_asset_turnover
- fur_roa



raw_means:
  - Turnover_mean
  - EBIT_mean
  - PLTax_mean
  # - MScore.
  - Leverage_mean
  - ROE_mean
  - TAsset_mean

categoricals:
- Company name
- Region
- Country
- NACE code
- Sector 1
- Sector 2
- Combined_Sector
- MScore_mean
- growth_MScore_mean
- volatility_MScore


raw_features:
  - Turnover.
  - EBIT.
  - PLTax.
  # - MScore.
  - Leverage.
  - ROE.
  - TAsset.

growth_features:
  - growth_TAsset
  - growth_EBIT
  # - growth_MScore.
  - growth_PLTax
  - growth_Turnover
  - growth_Leverage
  - growth_ROE

volatility_features:
  - volatility_TAsset
  - volatility_EBIT
  # - volatility_MScore
  - volatility_PLTax
  - volatility_Turnover
  - volatility_Leverage
  - volatility_ROE

further_features:
  - fur_debt_to_eq
  - fur_op_marg
  - fur_asset_turnover
  - fur_roa

trans_idx:
  # - log
  - sqrt
  - inv_sqrt
  - inv
  - power
